### ISSUE TITLE
Multiple patterns support

### ISSUE THREAD

**Issue by ghost** [Dashlane/node-find-glob#1]
Hello,
I'd like to ask you to implement (and document) support for specifying multiple input patterns. That would allow us to run `find-glob` from build (e.g. npm) scripts since we would like to pass the list of the patterns from an environment variable.

**Comment by radek-holy** [comment]
Also, it would be nice if the negative patterns (e.g. `!(node_modules)/**`) would negate the result of the previous patterns. You can use [glob-all](https://www.npmjs.com/package/glob-all) to achieve that. Actually, you can turn this into a command line interface to `glob-all` as requested here: https://github.com/jpillora/node-glob-all/issues/6.

**Comment by denis-sokolov** [comment]
You can already pass multiple input patterns. I shall make this clearer in the documentation, but if you run `find-glob -h`, you will see that: `find-glob *.json *.js`.
It does not allow for exclusion, though. Made #2 about that.

(In addition, by the way, node-glob itself allows conjunction: `find-glob '@(*.json|*.js)'.)

**Comment by radek-holy** [comment]
OK, thanks for the info.
