### ISSUE TITLE
Exclusion in multiple patterns

### ISSUE THREAD

**Issue by denis-sokolov** [Dashlane/node-find-glob#2]
Allow excluding patterns when multiple patterns have been provided. (Perhaps by using [`glob-all`](https://github.com/jpillora/node-glob-all))

**Comment by radek-holy** [comment]
FYI, I've just realized that `glob-all` is not the only module that provides this. `globby`, `globule` and `simple-glob` do that as well, IIUIC.

**Comment by denis-sokolov** [comment]
Released in 2.0.0.

**Comment by radek-holy** [comment]
Cool, thank you!
