### ISSUE TITLE
Read patterns from a file

### ISSUE THREAD

**Issue by ghost** [Dashlane/node-find-glob#3]
I just realized that there is no cross-platform way to use environment variables in NPM scripts. So, I guess that the only way to have a single source of file patterns is to store them in a file. Can you please consider adding a support to read the patterns from files? I'd leave it up to you whether to read them from standard input or from the file system. I also do not prefer any file format (simple text file, a JSON file, whatever...). And if I could specify multiple files, it would be even better.

If it does no sound reasonable, I can still use `xargs`, I guess... But you know... The shorter the script is, the better...

**Comment by denis-sokolov** [comment]
I'm sorry, I am of the opinion that small utilities should stay small and we should combine small utilities for our effect. Thus I'd suggest you stick to `xargs` for the benefit of stability of `find-glob`.

**Comment by denis-sokolov** [comment]
In fact, using `find-glob` with `xargs` is the primary use case how I use it. The point of it was to allow the traditional UNIX `find | xargs` workflow, but with more powerful glob patterns.

**Comment by radek-holy** [comment]
Sure, not a big problem. Thanks for considering.
